# Generated by Django 5.1.7 on 2025-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_transactioninvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='cart_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
