# Generated by Django 5.1.4 on 2025-01-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customerinvoice_user'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioninvoice',
            old_name='subtotal',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='transactioninvoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioninvoice',
            name='customer_invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.customerinvoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactioninvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactioninvoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
