# Generated by Django 5.1.7 on 2025-05-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customerinvoice_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='cart_discount',
        ),
    ]
