# Generated by Django 5.1.7 on 2025-05-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_customerinvoice_cart_discount'),
        ('store', '0003_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioninvoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='transactioninvoice',
            name='change',
        ),
        migrations.RemoveField(
            model_name='transactioninvoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='transactioninvoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
