# Generated by Django 5.1.4 on 2025-01-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_subtotal_transactioninvoice_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
