# Generated by Django 5.1.7 on 2025-05-14 00:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_transactioninvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
