# Generated by Django 5.1.4 on 2025-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customerinvoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
