# Generated by Django 5.1.7 on 2025-05-14 00:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_transactioninvoice_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
