# Generated by Django 5.1.4 on 2025-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_customerinvoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
