# Generated by Django 5.1.4 on 2025-01-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_customerinvoice_invoice_number'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactioninvoice',
            old_name='total',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='transactioninvoice',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
