# Generated by Django 5.1.7 on 2025-05-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_customerinvoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
