# Generated by Django 5.1.4 on 2025-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_rename_total_transactioninvoice_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
