# Generated by Django 5.1.7 on 2025-05-29 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_customerinvoice_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customerinvoice')),
            ],
        ),
    ]
