# Generated by Django 5.1.7 on 2025-05-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_invoice',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='customer_name',
            field=models.CharField(max_length=225),
        ),
    ]
