# Generated by Django 5.1.7 on 2025-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_customer_customer_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
