# Generated by Django 5.1.7 on 2025-06-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='customer',
        ),
    ]
