# Generated by Django 5.1.7 on 2025-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_customerinvoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer'),
        ),
    ]
