# Generated by Django 5.1.7 on 2025-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_customerinvoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
