# Generated by Django 5.1.7 on 2025-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_customerinvoice_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninvoice',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
