# Generated by Django 5.1.7 on 2025-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_transactioninvoice_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioninvoice',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
