runtime: python311

entrypoint: ./entrypoint.sh

env_variables:
  DJANGO_SETTINGS_MODULE: "boutique_POS.settings"
  SECRET_KEY: "Lu@582580"
  DB_NAME: "boutique_db"  # corrected DB name (underscore)
  DB_USER: "root"         # or your created DB user like "django_user"
  DB_PASSWORD: "Lu@582580"
  INSTANCE_CONNECTION_NAME: "boutique-pos-466509:europe-west1:boutique-db"  # corrected instance name

beta_settings:
  cloud_sql_instances: boutique-pos-466509:europe-west1:boutique-db  # corrected instance name

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /media
    static_dir: media

  - url: /.*
    script: auto
