# Generated by Django 5.1.6 on 2025-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('card', 'Card Payment'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='revenue',
            name='receipt_attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
