# Generated by Django 5.1.6 on 2025-02-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_revenue_payment_method_revenue_receipt_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='expenditure',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('card', 'Card Payment'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='receipt_attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
