# Generated by Django 5.1.7 on 2025-05-09 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_product_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_cp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='store.product')),
            ],
            options={
                'ordering': ['-date_changed'],
            },
        ),
    ]
